name: docs-build
on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # Fetch full history for git revision dates
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/requirements.txt -r requirements/requirements_dev.txt  -r requirements/requirements_docs.txt
                  pip install .
            - name: Discover typos with codespell
              run: codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff,*.pdf,./.git" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs"
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - name: Build docs
              run: |
                  mkdocs build
            # - name: Deploy to Netlify
            #   uses: nwtgck/actions-netlify@v2.0
            #   with:
            #       publish-dir: "./site"
            #       production-branch: master
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       deploy-message: "Deploy from GitHub Actions"
            #       enable-pull-request-comment: true
            #       enable-commit-comment: false
            #       overwrites-pull-request-comment: true
            #   env:
            #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            #   timeout-minutes: 10
